upstream ias_backend {
    server 10.0.46.75:3000;
    server 10.0.54.22:3000;
}

server {
    listen 80;
    server_name _;

    location = /health {
        access_log off;
        return 200 'healthy';
        add_header Content-Type text/plain;
    }

    location / {
        proxy_pass http://ias_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
